/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccessfulVerificationRouteImport } from './routes/successful-verification'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as R403RouteImport } from './routes/403'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutTicketRouteImport } from './routes/_layout/ticket'
import { Route as LayoutSearchRouteImport } from './routes/_layout/search'
import { Route as LayoutSlugRouteImport } from './routes/_layout/$slug'
import { Route as AuthTicketBookingRouteImport } from './routes/_auth/ticket-booking'
import { Route as AuthLayoutRouteImport } from './routes/_auth/_layout'
import { Route as AuthManagerLayoutRouteImport } from './routes/_auth/manager/_layout'
import { Route as AuthAdminLayoutRouteImport } from './routes/_auth/admin/_layout'
import { Route as AuthLayoutTicketScannerRouteImport } from './routes/_auth/_layout/ticket-scanner'
import { Route as AuthLayoutProfileRouteImport } from './routes/_auth/_layout/profile'
import { Route as AuthLayoutMyTicketsRouteImport } from './routes/_auth/_layout/my-tickets'
import { Route as AuthAdminLayoutIndexRouteImport } from './routes/_auth/admin/_layout/index'
import { Route as AuthManagerLayoutTicketScannerRouteImport } from './routes/_auth/manager/_layout/ticket-scanner'
import { Route as AuthManagerLayoutOrdersRouteImport } from './routes/_auth/manager/_layout/orders'
import { Route as AuthAdminLayoutUsersRouteImport } from './routes/_auth/admin/_layout/users'
import { Route as AuthAdminLayoutOrdersRouteImport } from './routes/_auth/admin/_layout/orders'
import { Route as AuthAdminLayoutEventTypesRouteImport } from './routes/_auth/admin/_layout/event-types'
import { Route as AuthAdminLayoutDashboardRouteImport } from './routes/_auth/admin/_layout/dashboard'
import { Route as AuthManagerLayoutEventsIndexRouteImport } from './routes/_auth/manager/_layout/events/index'
import { Route as AuthAdminLayoutEventsIndexRouteImport } from './routes/_auth/admin/_layout/events/index'
import { Route as AuthManagerLayoutEventsCreateRouteImport } from './routes/_auth/manager/_layout/events/create'
import { Route as AuthManagerLayoutEventsEventIdRouteImport } from './routes/_auth/manager/_layout/events/$eventId'
import { Route as AuthAdminLayoutEventsIdRouteImport } from './routes/_auth/admin/_layout/events/$id'
import { Route as AuthLayoutOrdersIdPaymentRouteImport } from './routes/_auth/_layout/orders/$id/payment'

const AuthManagerRouteImport = createFileRoute('/_auth/manager')()
const AuthAdminRouteImport = createFileRoute('/_auth/admin')()

const SuccessfulVerificationRoute = SuccessfulVerificationRouteImport.update({
  id: '/successful-verification',
  path: '/successful-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthManagerRoute = AuthManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRoute,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTicketRoute = LayoutTicketRouteImport.update({
  id: '/ticket',
  path: '/ticket',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSearchRoute = LayoutSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSlugRoute = LayoutSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LayoutRoute,
} as any)
const AuthTicketBookingRoute = AuthTicketBookingRouteImport.update({
  id: '/ticket-booking',
  path: '/ticket-booking',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AuthRoute,
} as any)
const AuthManagerLayoutRoute = AuthManagerLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AuthManagerRoute,
} as any)
const AuthAdminLayoutRoute = AuthAdminLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthLayoutTicketScannerRoute = AuthLayoutTicketScannerRouteImport.update({
  id: '/ticket-scanner',
  path: '/ticket-scanner',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutProfileRoute = AuthLayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutMyTicketsRoute = AuthLayoutMyTicketsRouteImport.update({
  id: '/my-tickets',
  path: '/my-tickets',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthAdminLayoutIndexRoute = AuthAdminLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAdminLayoutRoute,
} as any)
const AuthManagerLayoutTicketScannerRoute =
  AuthManagerLayoutTicketScannerRouteImport.update({
    id: '/ticket-scanner',
    path: '/ticket-scanner',
    getParentRoute: () => AuthManagerLayoutRoute,
  } as any)
const AuthManagerLayoutOrdersRoute = AuthManagerLayoutOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthManagerLayoutRoute,
} as any)
const AuthAdminLayoutUsersRoute = AuthAdminLayoutUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthAdminLayoutRoute,
} as any)
const AuthAdminLayoutOrdersRoute = AuthAdminLayoutOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthAdminLayoutRoute,
} as any)
const AuthAdminLayoutEventTypesRoute =
  AuthAdminLayoutEventTypesRouteImport.update({
    id: '/event-types',
    path: '/event-types',
    getParentRoute: () => AuthAdminLayoutRoute,
  } as any)
const AuthAdminLayoutDashboardRoute =
  AuthAdminLayoutDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthAdminLayoutRoute,
  } as any)
const AuthManagerLayoutEventsIndexRoute =
  AuthManagerLayoutEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => AuthManagerLayoutRoute,
  } as any)
const AuthAdminLayoutEventsIndexRoute =
  AuthAdminLayoutEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => AuthAdminLayoutRoute,
  } as any)
const AuthManagerLayoutEventsCreateRoute =
  AuthManagerLayoutEventsCreateRouteImport.update({
    id: '/events/create',
    path: '/events/create',
    getParentRoute: () => AuthManagerLayoutRoute,
  } as any)
const AuthManagerLayoutEventsEventIdRoute =
  AuthManagerLayoutEventsEventIdRouteImport.update({
    id: '/events/$eventId',
    path: '/events/$eventId',
    getParentRoute: () => AuthManagerLayoutRoute,
  } as any)
const AuthAdminLayoutEventsIdRoute = AuthAdminLayoutEventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => AuthAdminLayoutRoute,
} as any)
const AuthLayoutOrdersIdPaymentRoute =
  AuthLayoutOrdersIdPaymentRouteImport.update({
    id: '/orders/$id/payment',
    path: '/orders/$id/payment',
    getParentRoute: () => AuthLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/403': typeof R403Route
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/successful-verification': typeof SuccessfulVerificationRoute
  '/ticket-booking': typeof AuthTicketBookingRoute
  '/$slug': typeof LayoutSlugRoute
  '/search': typeof LayoutSearchRoute
  '/ticket': typeof LayoutTicketRoute
  '/': typeof LayoutIndexRoute
  '/my-tickets': typeof AuthLayoutMyTicketsRoute
  '/profile': typeof AuthLayoutProfileRoute
  '/ticket-scanner': typeof AuthLayoutTicketScannerRoute
  '/admin': typeof AuthAdminLayoutRouteWithChildren
  '/manager': typeof AuthManagerLayoutRouteWithChildren
  '/admin/dashboard': typeof AuthAdminLayoutDashboardRoute
  '/admin/event-types': typeof AuthAdminLayoutEventTypesRoute
  '/admin/orders': typeof AuthAdminLayoutOrdersRoute
  '/admin/users': typeof AuthAdminLayoutUsersRoute
  '/manager/orders': typeof AuthManagerLayoutOrdersRoute
  '/manager/ticket-scanner': typeof AuthManagerLayoutTicketScannerRoute
  '/admin/': typeof AuthAdminLayoutIndexRoute
  '/orders/$id/payment': typeof AuthLayoutOrdersIdPaymentRoute
  '/admin/events/$id': typeof AuthAdminLayoutEventsIdRoute
  '/manager/events/$eventId': typeof AuthManagerLayoutEventsEventIdRoute
  '/manager/events/create': typeof AuthManagerLayoutEventsCreateRoute
  '/admin/events': typeof AuthAdminLayoutEventsIndexRoute
  '/manager/events': typeof AuthManagerLayoutEventsIndexRoute
}
export interface FileRoutesByTo {
  '/403': typeof R403Route
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/successful-verification': typeof SuccessfulVerificationRoute
  '/ticket-booking': typeof AuthTicketBookingRoute
  '/$slug': typeof LayoutSlugRoute
  '/search': typeof LayoutSearchRoute
  '/ticket': typeof LayoutTicketRoute
  '/': typeof LayoutIndexRoute
  '/my-tickets': typeof AuthLayoutMyTicketsRoute
  '/profile': typeof AuthLayoutProfileRoute
  '/ticket-scanner': typeof AuthLayoutTicketScannerRoute
  '/admin': typeof AuthAdminLayoutIndexRoute
  '/manager': typeof AuthManagerLayoutRouteWithChildren
  '/admin/dashboard': typeof AuthAdminLayoutDashboardRoute
  '/admin/event-types': typeof AuthAdminLayoutEventTypesRoute
  '/admin/orders': typeof AuthAdminLayoutOrdersRoute
  '/admin/users': typeof AuthAdminLayoutUsersRoute
  '/manager/orders': typeof AuthManagerLayoutOrdersRoute
  '/manager/ticket-scanner': typeof AuthManagerLayoutTicketScannerRoute
  '/orders/$id/payment': typeof AuthLayoutOrdersIdPaymentRoute
  '/admin/events/$id': typeof AuthAdminLayoutEventsIdRoute
  '/manager/events/$eventId': typeof AuthManagerLayoutEventsEventIdRoute
  '/manager/events/create': typeof AuthManagerLayoutEventsCreateRoute
  '/admin/events': typeof AuthAdminLayoutEventsIndexRoute
  '/manager/events': typeof AuthManagerLayoutEventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/403': typeof R403Route
  '/_auth': typeof AuthRouteWithChildren
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/successful-verification': typeof SuccessfulVerificationRoute
  '/_auth/_layout': typeof AuthLayoutRouteWithChildren
  '/_auth/ticket-booking': typeof AuthTicketBookingRoute
  '/_layout/$slug': typeof LayoutSlugRoute
  '/_layout/search': typeof LayoutSearchRoute
  '/_layout/ticket': typeof LayoutTicketRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_auth/_layout/my-tickets': typeof AuthLayoutMyTicketsRoute
  '/_auth/_layout/profile': typeof AuthLayoutProfileRoute
  '/_auth/_layout/ticket-scanner': typeof AuthLayoutTicketScannerRoute
  '/_auth/admin': typeof AuthAdminRouteWithChildren
  '/_auth/admin/_layout': typeof AuthAdminLayoutRouteWithChildren
  '/_auth/manager': typeof AuthManagerRouteWithChildren
  '/_auth/manager/_layout': typeof AuthManagerLayoutRouteWithChildren
  '/_auth/admin/_layout/dashboard': typeof AuthAdminLayoutDashboardRoute
  '/_auth/admin/_layout/event-types': typeof AuthAdminLayoutEventTypesRoute
  '/_auth/admin/_layout/orders': typeof AuthAdminLayoutOrdersRoute
  '/_auth/admin/_layout/users': typeof AuthAdminLayoutUsersRoute
  '/_auth/manager/_layout/orders': typeof AuthManagerLayoutOrdersRoute
  '/_auth/manager/_layout/ticket-scanner': typeof AuthManagerLayoutTicketScannerRoute
  '/_auth/admin/_layout/': typeof AuthAdminLayoutIndexRoute
  '/_auth/_layout/orders/$id/payment': typeof AuthLayoutOrdersIdPaymentRoute
  '/_auth/admin/_layout/events/$id': typeof AuthAdminLayoutEventsIdRoute
  '/_auth/manager/_layout/events/$eventId': typeof AuthManagerLayoutEventsEventIdRoute
  '/_auth/manager/_layout/events/create': typeof AuthManagerLayoutEventsCreateRoute
  '/_auth/admin/_layout/events/': typeof AuthAdminLayoutEventsIndexRoute
  '/_auth/manager/_layout/events/': typeof AuthManagerLayoutEventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/403'
    | '/login'
    | '/sign-up'
    | '/successful-verification'
    | '/ticket-booking'
    | '/$slug'
    | '/search'
    | '/ticket'
    | '/'
    | '/my-tickets'
    | '/profile'
    | '/ticket-scanner'
    | '/admin'
    | '/manager'
    | '/admin/dashboard'
    | '/admin/event-types'
    | '/admin/orders'
    | '/admin/users'
    | '/manager/orders'
    | '/manager/ticket-scanner'
    | '/admin/'
    | '/orders/$id/payment'
    | '/admin/events/$id'
    | '/manager/events/$eventId'
    | '/manager/events/create'
    | '/admin/events'
    | '/manager/events'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/403'
    | '/login'
    | '/sign-up'
    | '/successful-verification'
    | '/ticket-booking'
    | '/$slug'
    | '/search'
    | '/ticket'
    | '/'
    | '/my-tickets'
    | '/profile'
    | '/ticket-scanner'
    | '/admin'
    | '/manager'
    | '/admin/dashboard'
    | '/admin/event-types'
    | '/admin/orders'
    | '/admin/users'
    | '/manager/orders'
    | '/manager/ticket-scanner'
    | '/orders/$id/payment'
    | '/admin/events/$id'
    | '/manager/events/$eventId'
    | '/manager/events/create'
    | '/admin/events'
    | '/manager/events'
  id:
    | '__root__'
    | '/403'
    | '/_auth'
    | '/_layout'
    | '/login'
    | '/sign-up'
    | '/successful-verification'
    | '/_auth/_layout'
    | '/_auth/ticket-booking'
    | '/_layout/$slug'
    | '/_layout/search'
    | '/_layout/ticket'
    | '/_layout/'
    | '/_auth/_layout/my-tickets'
    | '/_auth/_layout/profile'
    | '/_auth/_layout/ticket-scanner'
    | '/_auth/admin'
    | '/_auth/admin/_layout'
    | '/_auth/manager'
    | '/_auth/manager/_layout'
    | '/_auth/admin/_layout/dashboard'
    | '/_auth/admin/_layout/event-types'
    | '/_auth/admin/_layout/orders'
    | '/_auth/admin/_layout/users'
    | '/_auth/manager/_layout/orders'
    | '/_auth/manager/_layout/ticket-scanner'
    | '/_auth/admin/_layout/'
    | '/_auth/_layout/orders/$id/payment'
    | '/_auth/admin/_layout/events/$id'
    | '/_auth/manager/_layout/events/$eventId'
    | '/_auth/manager/_layout/events/create'
    | '/_auth/admin/_layout/events/'
    | '/_auth/manager/_layout/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  R403Route: typeof R403Route
  AuthRoute: typeof AuthRouteWithChildren
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignUpRoute: typeof SignUpRoute
  SuccessfulVerificationRoute: typeof SuccessfulVerificationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/successful-verification': {
      id: '/successful-verification'
      path: '/successful-verification'
      fullPath: '/successful-verification'
      preLoaderRoute: typeof SuccessfulVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/manager': {
      id: '/_auth/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof AuthManagerRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin': {
      id: '/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/ticket': {
      id: '/_layout/ticket'
      path: '/ticket'
      fullPath: '/ticket'
      preLoaderRoute: typeof LayoutTicketRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/search': {
      id: '/_layout/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof LayoutSearchRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$slug': {
      id: '/_layout/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof LayoutSlugRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_auth/ticket-booking': {
      id: '/_auth/ticket-booking'
      path: '/ticket-booking'
      fullPath: '/ticket-booking'
      preLoaderRoute: typeof AuthTicketBookingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_layout': {
      id: '/_auth/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/manager/_layout': {
      id: '/_auth/manager/_layout'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof AuthManagerLayoutRouteImport
      parentRoute: typeof AuthManagerRoute
    }
    '/_auth/admin/_layout': {
      id: '/_auth/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminLayoutRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/_layout/ticket-scanner': {
      id: '/_auth/_layout/ticket-scanner'
      path: '/ticket-scanner'
      fullPath: '/ticket-scanner'
      preLoaderRoute: typeof AuthLayoutTicketScannerRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/profile': {
      id: '/_auth/_layout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthLayoutProfileRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/my-tickets': {
      id: '/_auth/_layout/my-tickets'
      path: '/my-tickets'
      fullPath: '/my-tickets'
      preLoaderRoute: typeof AuthLayoutMyTicketsRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/admin/_layout/': {
      id: '/_auth/admin/_layout/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthAdminLayoutIndexRouteImport
      parentRoute: typeof AuthAdminLayoutRoute
    }
    '/_auth/manager/_layout/ticket-scanner': {
      id: '/_auth/manager/_layout/ticket-scanner'
      path: '/ticket-scanner'
      fullPath: '/manager/ticket-scanner'
      preLoaderRoute: typeof AuthManagerLayoutTicketScannerRouteImport
      parentRoute: typeof AuthManagerLayoutRoute
    }
    '/_auth/manager/_layout/orders': {
      id: '/_auth/manager/_layout/orders'
      path: '/orders'
      fullPath: '/manager/orders'
      preLoaderRoute: typeof AuthManagerLayoutOrdersRouteImport
      parentRoute: typeof AuthManagerLayoutRoute
    }
    '/_auth/admin/_layout/users': {
      id: '/_auth/admin/_layout/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthAdminLayoutUsersRouteImport
      parentRoute: typeof AuthAdminLayoutRoute
    }
    '/_auth/admin/_layout/orders': {
      id: '/_auth/admin/_layout/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthAdminLayoutOrdersRouteImport
      parentRoute: typeof AuthAdminLayoutRoute
    }
    '/_auth/admin/_layout/event-types': {
      id: '/_auth/admin/_layout/event-types'
      path: '/event-types'
      fullPath: '/admin/event-types'
      preLoaderRoute: typeof AuthAdminLayoutEventTypesRouteImport
      parentRoute: typeof AuthAdminLayoutRoute
    }
    '/_auth/admin/_layout/dashboard': {
      id: '/_auth/admin/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthAdminLayoutDashboardRouteImport
      parentRoute: typeof AuthAdminLayoutRoute
    }
    '/_auth/manager/_layout/events/': {
      id: '/_auth/manager/_layout/events/'
      path: '/events'
      fullPath: '/manager/events'
      preLoaderRoute: typeof AuthManagerLayoutEventsIndexRouteImport
      parentRoute: typeof AuthManagerLayoutRoute
    }
    '/_auth/admin/_layout/events/': {
      id: '/_auth/admin/_layout/events/'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AuthAdminLayoutEventsIndexRouteImport
      parentRoute: typeof AuthAdminLayoutRoute
    }
    '/_auth/manager/_layout/events/create': {
      id: '/_auth/manager/_layout/events/create'
      path: '/events/create'
      fullPath: '/manager/events/create'
      preLoaderRoute: typeof AuthManagerLayoutEventsCreateRouteImport
      parentRoute: typeof AuthManagerLayoutRoute
    }
    '/_auth/manager/_layout/events/$eventId': {
      id: '/_auth/manager/_layout/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/manager/events/$eventId'
      preLoaderRoute: typeof AuthManagerLayoutEventsEventIdRouteImport
      parentRoute: typeof AuthManagerLayoutRoute
    }
    '/_auth/admin/_layout/events/$id': {
      id: '/_auth/admin/_layout/events/$id'
      path: '/events/$id'
      fullPath: '/admin/events/$id'
      preLoaderRoute: typeof AuthAdminLayoutEventsIdRouteImport
      parentRoute: typeof AuthAdminLayoutRoute
    }
    '/_auth/_layout/orders/$id/payment': {
      id: '/_auth/_layout/orders/$id/payment'
      path: '/orders/$id/payment'
      fullPath: '/orders/$id/payment'
      preLoaderRoute: typeof AuthLayoutOrdersIdPaymentRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
  }
}

interface AuthLayoutRouteChildren {
  AuthLayoutMyTicketsRoute: typeof AuthLayoutMyTicketsRoute
  AuthLayoutProfileRoute: typeof AuthLayoutProfileRoute
  AuthLayoutTicketScannerRoute: typeof AuthLayoutTicketScannerRoute
  AuthLayoutOrdersIdPaymentRoute: typeof AuthLayoutOrdersIdPaymentRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutMyTicketsRoute: AuthLayoutMyTicketsRoute,
  AuthLayoutProfileRoute: AuthLayoutProfileRoute,
  AuthLayoutTicketScannerRoute: AuthLayoutTicketScannerRoute,
  AuthLayoutOrdersIdPaymentRoute: AuthLayoutOrdersIdPaymentRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface AuthAdminLayoutRouteChildren {
  AuthAdminLayoutDashboardRoute: typeof AuthAdminLayoutDashboardRoute
  AuthAdminLayoutEventTypesRoute: typeof AuthAdminLayoutEventTypesRoute
  AuthAdminLayoutOrdersRoute: typeof AuthAdminLayoutOrdersRoute
  AuthAdminLayoutUsersRoute: typeof AuthAdminLayoutUsersRoute
  AuthAdminLayoutIndexRoute: typeof AuthAdminLayoutIndexRoute
  AuthAdminLayoutEventsIdRoute: typeof AuthAdminLayoutEventsIdRoute
  AuthAdminLayoutEventsIndexRoute: typeof AuthAdminLayoutEventsIndexRoute
}

const AuthAdminLayoutRouteChildren: AuthAdminLayoutRouteChildren = {
  AuthAdminLayoutDashboardRoute: AuthAdminLayoutDashboardRoute,
  AuthAdminLayoutEventTypesRoute: AuthAdminLayoutEventTypesRoute,
  AuthAdminLayoutOrdersRoute: AuthAdminLayoutOrdersRoute,
  AuthAdminLayoutUsersRoute: AuthAdminLayoutUsersRoute,
  AuthAdminLayoutIndexRoute: AuthAdminLayoutIndexRoute,
  AuthAdminLayoutEventsIdRoute: AuthAdminLayoutEventsIdRoute,
  AuthAdminLayoutEventsIndexRoute: AuthAdminLayoutEventsIndexRoute,
}

const AuthAdminLayoutRouteWithChildren = AuthAdminLayoutRoute._addFileChildren(
  AuthAdminLayoutRouteChildren,
)

interface AuthAdminRouteChildren {
  AuthAdminLayoutRoute: typeof AuthAdminLayoutRouteWithChildren
}

const AuthAdminRouteChildren: AuthAdminRouteChildren = {
  AuthAdminLayoutRoute: AuthAdminLayoutRouteWithChildren,
}

const AuthAdminRouteWithChildren = AuthAdminRoute._addFileChildren(
  AuthAdminRouteChildren,
)

interface AuthManagerLayoutRouteChildren {
  AuthManagerLayoutOrdersRoute: typeof AuthManagerLayoutOrdersRoute
  AuthManagerLayoutTicketScannerRoute: typeof AuthManagerLayoutTicketScannerRoute
  AuthManagerLayoutEventsEventIdRoute: typeof AuthManagerLayoutEventsEventIdRoute
  AuthManagerLayoutEventsCreateRoute: typeof AuthManagerLayoutEventsCreateRoute
  AuthManagerLayoutEventsIndexRoute: typeof AuthManagerLayoutEventsIndexRoute
}

const AuthManagerLayoutRouteChildren: AuthManagerLayoutRouteChildren = {
  AuthManagerLayoutOrdersRoute: AuthManagerLayoutOrdersRoute,
  AuthManagerLayoutTicketScannerRoute: AuthManagerLayoutTicketScannerRoute,
  AuthManagerLayoutEventsEventIdRoute: AuthManagerLayoutEventsEventIdRoute,
  AuthManagerLayoutEventsCreateRoute: AuthManagerLayoutEventsCreateRoute,
  AuthManagerLayoutEventsIndexRoute: AuthManagerLayoutEventsIndexRoute,
}

const AuthManagerLayoutRouteWithChildren =
  AuthManagerLayoutRoute._addFileChildren(AuthManagerLayoutRouteChildren)

interface AuthManagerRouteChildren {
  AuthManagerLayoutRoute: typeof AuthManagerLayoutRouteWithChildren
}

const AuthManagerRouteChildren: AuthManagerRouteChildren = {
  AuthManagerLayoutRoute: AuthManagerLayoutRouteWithChildren,
}

const AuthManagerRouteWithChildren = AuthManagerRoute._addFileChildren(
  AuthManagerRouteChildren,
)

interface AuthRouteChildren {
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  AuthTicketBookingRoute: typeof AuthTicketBookingRoute
  AuthAdminRoute: typeof AuthAdminRouteWithChildren
  AuthManagerRoute: typeof AuthManagerRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  AuthTicketBookingRoute: AuthTicketBookingRoute,
  AuthAdminRoute: AuthAdminRouteWithChildren,
  AuthManagerRoute: AuthManagerRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface LayoutRouteChildren {
  LayoutSlugRoute: typeof LayoutSlugRoute
  LayoutSearchRoute: typeof LayoutSearchRoute
  LayoutTicketRoute: typeof LayoutTicketRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutSlugRoute: LayoutSlugRoute,
  LayoutSearchRoute: LayoutSearchRoute,
  LayoutTicketRoute: LayoutTicketRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  R403Route: R403Route,
  AuthRoute: AuthRouteWithChildren,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  SignUpRoute: SignUpRoute,
  SuccessfulVerificationRoute: SuccessfulVerificationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
